export const BUSCAR_JUEGO = 'BUSCAR_JUEGO';
export const OBTENER_DETALLES_JUEGO = 'OBTENER_DETALLES_JUEGO';
export const FILTRAR_POR_GENERO = 'FILTRAR_POR_GENERO'
export const ORDENAR_POR_NOMBRE_DES = 'ORDENAR_POR_NOMBRE_DES';
export const ORDENAR_POR_NOMBRE_AS = 'ORDENAR_POR_NOMBRE_AS';
export const ORDENAR_POR_RATING_AS = 'ORDENAR_POR_RATING_AS';
export const ORDENAR_POR_RATING_DES = 'ORDENAR_POR_RATING_DES';
